#!/usr/bin/env bash

set -e 

cd
mkdir -p teach_and_repeat_ws/src
cd teach_and_repeat_ws/src
catkin_init_workspace
cd ..
catkin_make
source devel/setup.bash
echo "source ~/teach_and_repeat_ws/devel/setup.bash" >> ~/.bashrc
source ~/.bashrc
sudo apt-get install ros-indigo-libnabo
sudo apt-get remove ros-indigo-libpointmatcher

cd src
git clone https://github.com/grassjelly/pointmatcher-ros
cd /tmp
git clone https://github.com/grassjelly/libpointmatcher
cd libpointmatcher
mkdir build
cd build
cmake ..
make
sudo make install
cd ~/teach_and_repeat_ws
catkin_make
source ~/.bashrc

cd src
git clone https://github.com/grassjelly/husky-trainer
cd ..
catkin_make
